export MasterPage from './MasterPage.js'
export IndexPage from './IndexPage.js'
export LoginPage from './LoginPage.js'
export RegistrationPage from './RegistrationPage.js'
export ProfilePage from './ProfilePage.js'
